# Package tweaks
- name: Faster dnf
  become: yes
  become_method: sudo
  ini_file:
    path: /etc/dnf/dnf.conf
    section: main
    option: fastestmirror
    value: true

- name: Update pre-installed packages
  become: yes
  become_method: sudo
  dnf:
    name: '*'
    state: latest

- name: dnf cleanup
  become: yes
  become_method: sudo
  dnf:
    autoremove: yes

- name: install yadm
  block:
  - name: clone yadm
    ansible.builtin.git:
      repo: 'https://github.com/TheLocehiliosan/yadm.git'
      dest: '{{ ansible_env.HOME }}/.local/installs/yadm'
      version: master
  - name: link yadm
    ansible.builtin.file:
      src: '{{ ansible_env.HOME }}/.local/installs/yadm/yadm'
      dest: '{{ ansible_evn.HOME }}/bin/yadm
      state: link

- name: yadm clone
  command: 'yadm clone {{ yadm_repo }}'
  when: yadm_repo is defined
  args:
      creates: '{{ ansible_env.HOME }}/.yadm'

- name: pyadm clone
  command: 'yadm clone --yadm-dir {{ ansible_env.HOME }}/.pyadm {{ pyadm_repo }}'
  when: pyadm_repo is defined
  args:
      creates: '{{ ansible_env.HOME }}/.pyadm'

# ssh lockdown
- name: Disable Password Authentication
  become: yes
  become_method: sudo
  lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^PasswordAuthentication'
        line: "PasswordAuthentication no"
        state: present
        backup: yes
        validate: /usr/sbin/sshd -t -f %s
  notify:
  - restart ssh

- name: Disable ChallengeResponse Authentication
  become: yes
  become_method: sudo
  lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^ChallengeResponseAuthentication'
        line: "ChallengeResponseAuthentication no"
        state: present
        backup: yes
        validate: /usr/sbin/sshd -t -f %s
  notify:
  - restart ssh

- name: Disable Root Login
  become: yes
  become_method: sudo
  lineinfile:
        dest: /etc/ssh/sshd_config
        regexp: '^PermitRootLogin'
        line: "PermitRootLogin no"
        state: present
        backup: yes
        validate: /usr/sbin/sshd -t -f %s
  notify:
    - restart ssh

- name: SSD trim
  become: yes
  become_method: sudo
  service:
      name=fstrim.timer
      enabled=yes

- name: Add the flathub flatpak repository remote to the user installation
  flatpak_remote:
    name: flathub
    state: present
    flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo
    method: user

- name: Install the flatpaks from flathub for current user
  flatpak:
    name: '{{ item }}'
    state: present
  loop:
  - org.gnome.Evolution
  - org.inkscape.Inkscape
  - org.keepassxc.KeePassXC
  - org.libreoffice.LibreOffice
  - org.mozilla.firefox
  - com.slack.Slack
  - org.zotero.Zotero
