- name: Basic packages
  become: yes
  become_method: sudo
  dnf:
    name:
    - kf5-plasma-devel
    - okular
    state: latest

- name: Unwanted KDE packages
  become: yes
  become_method: sudo
  dnf:
    name:
    - akgregator
    - kget
    - kmail
    - knode
    - konqueror
    - kontact
    state: absent

- name: dnf cleanup
  become: yes
  become_method: sudo
  dnf:
    autoremove: yes

- name: KDE widgets
  include_role:
    name: fedora
    tasks_from: kde_widgets
  loop:
  - repo: https://github.com/dfaust/plasma-applet-netspeed-widget
    name: org.kde.netspeedWidget
  loop_control:
    loop_var: widget

- name: Configure Plasma shell
  block:
  - tempfile:
      state: file
    register: plasma_js
    changed_when: false
  - copy:
      src: configure_plasma_shell.js
      dest: '{{ plasma_js.path }}'
    changed_when: false
  - shell: 'qdbus org.kde.plasmashell /PlasmaShell org.kde.PlasmaShell.evaluateScript "$(<{{ plasma_js.path }})"'
    args:
        executable: /bin/bash
    # TODO: any easy way to tell when this changed?
    changed_when: false

- name: Partial INI configs
  include_role:
    name: fedora
    tasks_from: partial_ini
  loop: "{{ query('filetree', 'ini_updates') }}"
  loop_control:
    loop_var: ini_item
  when: ini_item.state == 'file'
